package mx.ecomerce.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Valor generated by hbm2java
 */
@Entity
@Table(name = "Valor", catalog = "ECommerce")
public class Valor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String valor;
	private AtributoCategoria atributoCategoria;
	private CategoriaProducto categoriaProducto;
	
	public Valor() {
	}

	public Valor(AtributoCategoria atributoCategoria, CategoriaProducto categoriaProducto, String valor) {
		this.atributoCategoria = atributoCategoria;
		this.categoriaProducto = categoriaProducto;
		this.valor = valor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "valor", nullable = false, length = 200)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "Atributo_Categoriaid", referencedColumnName = "id")
	public AtributoCategoria getAtributoCategoria() {
		return atributoCategoria;
	}

	public void setAtributoCategoria(AtributoCategoria atributoCategoria) {
		this.atributoCategoria = atributoCategoria;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "Categoria_Productoid", referencedColumnName = "id")
	public CategoriaProducto getCategoriaProducto() {
		return categoriaProducto;
	}

	public void setCategoriaProducto(CategoriaProducto categoriaProducto) {
		this.categoriaProducto = categoriaProducto;
	}

	
}
