CREATE DATABASE ECommerce;
USE ECommerce;
CREATE TABLE Estado (id int(10) NOT NULL AUTO_INCREMENT, nombre varchar(50) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE Compra_Producto (id int(10) NOT NULL AUTO_INCREMENT, Compraid int(10) NOT NULL, Productoid int(10) NOT NULL, cantidad int(11) NOT NULL, PRIMARY KEY (id));
CREATE TABLE Compra (id int(10) NOT NULL AUTO_INCREMENT, fecha date NOT NULL, Estadoid int(10) NOT NULL, Usuarioid int(11), PRIMARY KEY (id));
CREATE TABLE Perfil (id int(10) NOT NULL AUTO_INCREMENT, nombre varchar(50) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE Valor (id int(10) NOT NULL AUTO_INCREMENT, Atributo_Categoriaid int(10) NOT NULL, Categoria_Productoid int(10) NOT NULL, valor varchar(200) NOT NULL, PRIMARY KEY (id));
CREATE TABLE Atributo_Categoria (id int(10) NOT NULL AUTO_INCREMENT, Atributoid int(10) NOT NULL, Categoriaid int(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE Categoria_Producto (id int(10) NOT NULL AUTO_INCREMENT, Categoriaid int(10) NOT NULL, Productoid int(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE Usuario (id int(11) NOT NULL AUTO_INCREMENT, correo varchar(20) NOT NULL UNIQUE, nombre varchar(50) NOT NULL, ap_paterno varchar(50) NOT NULL, ap_materno varchar(50) NOT NULL, password varchar(20) NOT NULL, Perfilid int(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE Categoria (id int(10) NOT NULL AUTO_INCREMENT, nombre varchar(50) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE Producto (id int(10) NOT NULL AUTO_INCREMENT, nombre varchar(50) NOT NULL UNIQUE, cantidad int(11) NOT NULL, precio float NOT NULL, PRIMARY KEY (id));
CREATE TABLE Atributo (id int(10) NOT NULL AUTO_INCREMENT, nombre varchar(50) NOT NULL UNIQUE, PRIMARY KEY (id));
ALTER TABLE Categoria_Producto ADD INDEX FKCategoria_925387 (Categoriaid), ADD CONSTRAINT FKCategoria_925387 FOREIGN KEY (Categoriaid) REFERENCES Categoria (id);
ALTER TABLE Categoria_Producto ADD INDEX FKCategoria_278445 (Productoid), ADD CONSTRAINT FKCategoria_278445 FOREIGN KEY (Productoid) REFERENCES Producto (id) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE Atributo_Categoria ADD INDEX FKAtributo_C797702 (Atributoid), ADD CONSTRAINT FKAtributo_C797702 FOREIGN KEY (Atributoid) REFERENCES Atributo (id) ON UPDATE Cascade ON DELETE Restrict;
ALTER TABLE Atributo_Categoria ADD INDEX FKAtributo_C729040 (Categoriaid), ADD CONSTRAINT FKAtributo_C729040 FOREIGN KEY (Categoriaid) REFERENCES Categoria (id) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE Valor ADD INDEX FKValor438707 (Atributo_Categoriaid), ADD CONSTRAINT FKValor438707 FOREIGN KEY (Atributo_Categoriaid) REFERENCES Atributo_Categoria (id) ON UPDATE Cascade ON DELETE Restrict;
ALTER TABLE Valor ADD INDEX FKValor915615 (Categoria_Productoid), ADD CONSTRAINT FKValor915615 FOREIGN KEY (Categoria_Productoid) REFERENCES Categoria_Producto (id) ON UPDATE Cascade ON DELETE Restrict;
ALTER TABLE Usuario ADD INDEX FKUsuario572115 (Perfilid), ADD CONSTRAINT FKUsuario572115 FOREIGN KEY (Perfilid) REFERENCES Perfil (id) ON UPDATE Cascade ON DELETE Restrict;
ALTER TABLE Compra ADD INDEX FKCompra920516 (Usuarioid), ADD CONSTRAINT FKCompra920516 FOREIGN KEY (Usuarioid) REFERENCES Usuario (id) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE Compra_Producto ADD INDEX FKCompra_Pro332911 (Compraid), ADD CONSTRAINT FKCompra_Pro332911 FOREIGN KEY (Compraid) REFERENCES Compra (id) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE Compra_Producto ADD INDEX FKCompra_Pro661485 (Productoid), ADD CONSTRAINT FKCompra_Pro661485 FOREIGN KEY (Productoid) REFERENCES Producto (id) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE Compra ADD INDEX FKCompra553160 (Estadoid), ADD CONSTRAINT FKCompra553160 FOREIGN KEY (Estadoid) REFERENCES Estado (id) ON UPDATE Cascade ON DELETE Restrict;
